### ISSUE TITLE
No license

### ISSUE THREAD

**Issue by j2l** [lunarmoon26/UnityPresentationFramework#1]
Hi Jack, 
Interesting, but you need to select a license.
Usually github offers MIT because it's the best choice but it's up to you.

**Comment by lunarmoon26** [comment]
Hi Phil,
Thank you for your suggestion. Yes I will and let you know.
Recently has been quite packed with my job..

**Comment by lunarmoon26** [comment]
Hi Phil,
License added

**Comment by j2l** [comment]
Great!
